name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACHYDERM_CLUSTER_URL: grpcs://hub-c0-fl3rezqasn.clusters.pachyderm.io:31400
      PACHYDERM_TOKEN: ${{ secrets.PACHYDERM_TOKEN }}
      DOCKER_IMAGE_NAME: pachyderm/housing-prices
      PACHYDERM_PIPELINE_FILES: regression.json
    steps:
      - name: pachyderm-update-pipelines
        uses: ./pachyderm-github-action
        id: pup
        with:
          pipeline-configs: |
            regression/pach-action.json
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          pachyderm-cluster-url: ${{ secrets.PACHYDERM_CLUSTER_URL }}
