name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pachyderm-update-pipelines
        uses: bbonenfant/pachyderm-gha/pachyderm-github-action@hackathon-2024
        id: pup
        with:
          pipeline-configs: |
            regression/pach-action.json
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          pachyderm-cluster-url: ${{ secrets.PACHYDERM_CLUSTER_URL }}
